name       : zotero
version    : 6.0.8
release    : 2
source     :
    - git|https://github.com/zotero/zotero.git : 6.0.8
    - git|https://github.com/zotero/zotero-build.git : 87e125bedcb3a01194013e207eff39d4e6deec92
    - git|https://github.com/zotero/zotero-standalone-build.git : 6.0.6
license    : AGPL-3.0-or-later
component  : office.scientific
summary    : Free, easy-to-use tool to help you collect, organize, cite, and share your research sources
description: |
    Free, easy-to-use tool to help you collect, organize, cite, and share your research sources
networking : yes
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libturbojpeg)
    - pkgconfig(python3)
    - pkgconfig(xt)
    - nodejs
    - rsync
    - wget
setup      : |
    mkdir -p $workdir/zotero-client
    mv `ls -A | grep -v zotero-client` $workdir/zotero-client
    cp -R $sources/zotero-build.git $workdir/zotero-build
    cp -R $sources/zotero-standalone-build.git $workdir/zotero-standalone-build
    cd $workdir/zotero-client
    git submodule init && git submodule update
    cd $workdir/zotero-build
    git submodule init && git submodule update
    cd $workdir/zotero-standalone-build
    git submodule init && git submodule update    
build      : |
    cd $workdir/zotero-client/
    npm i
    npm run build
    cd $workdir/zotero-standalone-build/
    ./fetch_xulrunner.sh -p l
    ./fetch_pdftools
    ./scripts/dir_build
install    : |
    install -dDm00755 $installdir/usr/{bin,lib/zotero}
    mv $workdir/zotero-standalone-build/staging/Zotero_linux-x86_64/* $installdir/usr/lib/zotero
    ln -s /usr/lib/zotero/zotero $installdir/usr/bin/zotero
    install -Dm00755 $pkgfiles/zotero.desktop $installdir/usr/share/applications/zotero.desktop
    rm $installdir/usr/lib/zotero/zotero.desktop
    sed -i '/pref("app.update.enabled", true);/c\pref("app.update.enabled", false);' $installdir/usr/lib/zotero/defaults/preferences/prefs.js
